# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_helloextendr_wrappers", use_symbols = TRUE, package_name = "helloextendr")

#' @docType package
#' @usage NULL
#' @useDynLib helloextendr, .registration = TRUE
NULL

MyClass <- new.env(parent = emptyenv())

MyClass$new <- function() .Call(wrap__MyClass__new)

MyClass$usize_implicit_conversion_implicit_errorhandling <- function(x) .Call(wrap__MyClass__usize_implicit_conversion_implicit_errorhandling, x)

MyClass$usize_implicit_conversion_explicit_errorhandling <- function(x) .Call(wrap__MyClass__usize_implicit_conversion_explicit_errorhandling, x)

#' @export
`$.MyClass` <- function (self, name) { func <- MyClass[[name]]; environment(func) <- environment(); func }

#' @export
`[[.MyClass` <- `$.MyClass`


# nolint end
