# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_helloextendr_wrappers", use_symbols = TRUE, package_name = "helloextendr")

#' @docType package
#' @usage NULL
#' @useDynLib helloextendr, .registration = TRUE
NULL

BobbyJoeString <- new.env(parent = emptyenv())

BobbyJoeString$new <- function() .Call(wrap__BobbyJoeString__new)

BobbyJoeString$print <- function() invisible(.Call(wrap__BobbyJoeString__print, self))

#' @export
`$.BobbyJoeString` <- function (self, name) { func <- BobbyJoeString[[name]]; environment(func) <- environment(); func }

#' @export
`[[.BobbyJoeString` <- `$.BobbyJoeString`


# nolint end
